//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.ServerHost.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDatabaseService")]
    public interface IDatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBooks", ReplyAction="http://tempuri.org/IDatabaseService/GetBooksResponse")]
        Library.DomainService.Objects.BookDto[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBooks", ReplyAction="http://tempuri.org/IDatabaseService/GetBooksResponse")]
        System.Threading.Tasks.Task<Library.DomainService.Objects.BookDto[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddBook", ReplyAction="http://tempuri.org/IDatabaseService/AddBookResponse")]
        Library.DomainService.Objects.ServiceResult AddBook(Library.DomainService.Objects.BookDto book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/AddBook", ReplyAction="http://tempuri.org/IDatabaseService/AddBookResponse")]
        System.Threading.Tasks.Task<Library.DomainService.Objects.ServiceResult> AddBookAsync(Library.DomainService.Objects.BookDto book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBookById", ReplyAction="http://tempuri.org/IDatabaseService/GetBookByIdResponse")]
        Library.DomainService.Objects.BookDto GetBookById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/GetBookById", ReplyAction="http://tempuri.org/IDatabaseService/GetBookByIdResponse")]
        System.Threading.Tasks.Task<Library.DomainService.Objects.BookDto> GetBookByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteBook", ReplyAction="http://tempuri.org/IDatabaseService/DeleteBookResponse")]
        Library.DomainService.Objects.ServiceResult DeleteBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseService/DeleteBook", ReplyAction="http://tempuri.org/IDatabaseService/DeleteBookResponse")]
        System.Threading.Tasks.Task<Library.DomainService.Objects.ServiceResult> DeleteBookAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabaseServiceChannel : Library.ServerHost.ServiceReference1.IDatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseServiceClient : System.ServiceModel.ClientBase<Library.ServerHost.ServiceReference1.IDatabaseService>, Library.ServerHost.ServiceReference1.IDatabaseService {
        
        public DatabaseServiceClient() {
        }
        
        public DatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Library.DomainService.Objects.BookDto[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<Library.DomainService.Objects.BookDto[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public Library.DomainService.Objects.ServiceResult AddBook(Library.DomainService.Objects.BookDto book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task<Library.DomainService.Objects.ServiceResult> AddBookAsync(Library.DomainService.Objects.BookDto book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public Library.DomainService.Objects.BookDto GetBookById(int id) {
            return base.Channel.GetBookById(id);
        }
        
        public System.Threading.Tasks.Task<Library.DomainService.Objects.BookDto> GetBookByIdAsync(int id) {
            return base.Channel.GetBookByIdAsync(id);
        }
        
        public Library.DomainService.Objects.ServiceResult DeleteBook(int id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<Library.DomainService.Objects.ServiceResult> DeleteBookAsync(int id) {
            return base.Channel.DeleteBookAsync(id);
        }
    }
}
